import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Data-access object that persists {@link PlayerProfile} records in an H2
 * database (file-based by default, in-memory when a test URL is supplied).
 *
 * <p>The database is created automatically on first use. Pass a custom JDBC
 * URL to the constructor to use an in-memory instance during tests:
 * <pre>{@code
 *   PlayerRepository repo = new PlayerRepository("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1");
 * }</pre>
 *
 * @author Tom Burchell
 * @version 1.0
 */
public class PlayerRepository {

    /** Default file-based database URL. */
    private static final String DEFAULT_URL = "jdbc:h2:./player_profiles";

    private final String url;
    private final String user;
    private final String password;

    /**
     * Opens (or creates) the default file-based database.
     */
    public PlayerRepository() {
        this(DEFAULT_URL, "sa", "");
    }

    /**
     * Opens (or creates) a database at the given JDBC URL.
     *
     * @param dbUrl    JDBC connection URL
     * @param user     database user
     * @param password database password
     */
    public PlayerRepository(String dbUrl, String user, String password) {
        this.url      = dbUrl;
        this.user     = user;
        this.password = password;
        createTable();
    }

    // ── Internal helpers ─────────────────────────────────────────────────────

    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(url, user, password);
    }

    private void createTable() {
        String sql = """
            CREATE TABLE IF NOT EXISTS players (
                id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name    VARCHAR(100) NOT NULL,
                balance INTEGER      NOT NULL DEFAULT 1000,
                wins    INTEGER      NOT NULL DEFAULT 0,
                losses  INTEGER      NOT NULL DEFAULT 0,
                ties    INTEGER      NOT NULL DEFAULT 0
            )
            """;
        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute(sql);
        } catch (SQLException e) {
            throw new RuntimeException("Failed to create players table", e);
        }
    }

    private static PlayerProfile mapRow(ResultSet rs) throws SQLException {
        PlayerProfile p = new PlayerProfile(rs.getString("name"), rs.getInt("balance"));
        p.setId(rs.getInt("id"));
        p.setWins(rs.getInt("wins"));
        p.setLosses(rs.getInt("losses"));
        p.setTies(rs.getInt("ties"));
        return p;
    }

    // ── CRUD operations ──────────────────────────────────────────────────────

    /**
     * Persists a new player profile and sets its generated {@code id}.
     *
     * @param profile profile to save (id is ignored and replaced)
     * @return the saved profile with its assigned id
     */
    public PlayerProfile save(PlayerProfile profile) {
        String sql = "INSERT INTO players (name, balance, wins, losses, ties) VALUES (?,?,?,?,?)";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, profile.getName());
            ps.setInt(2, profile.getBalance());
            ps.setInt(3, profile.getWins());
            ps.setInt(4, profile.getLosses());
            ps.setInt(5, profile.getTies());
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) {
                    profile.setId(keys.getInt(1));
                }
            }
            return profile;
        } catch (SQLException e) {
            throw new RuntimeException("Failed to save player", e);
        }
    }

    /**
     * Retrieves a player by their primary key.
     *
     * @param id player id
     * @return the {@link PlayerProfile}, or {@code null} if not found
     */
    public PlayerProfile findById(int id) {
        String sql = "SELECT * FROM players WHERE id = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return mapRow(rs);
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to find player by id", e);
        }
        return null;
    }

    /**
     * Retrieves a player by their exact name (first match).
     *
     * @param name player name
     * @return the {@link PlayerProfile}, or {@code null} if not found
     */
    public PlayerProfile findByName(String name) {
        String sql = "SELECT * FROM players WHERE name = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, name);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return mapRow(rs);
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to find player by name", e);
        }
        return null;
    }

    /**
     * Returns all player profiles, ordered by id ascending.
     *
     * @return list of all profiles (may be empty)
     */
    public List<PlayerProfile> findAll() {
        String sql = "SELECT * FROM players ORDER BY id";
        List<PlayerProfile> list = new ArrayList<>();
        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) list.add(mapRow(rs));
        } catch (SQLException e) {
            throw new RuntimeException("Failed to list players", e);
        }
        return list;
    }

    /**
     * Updates an existing player profile.
     *
     * @param profile profile to update (must have a valid id)
     * @return {@code true} if the row was updated, {@code false} if not found
     */
    public boolean update(PlayerProfile profile) {
        String sql = "UPDATE players SET name=?, balance=?, wins=?, losses=?, ties=? WHERE id=?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, profile.getName());
            ps.setInt(2, profile.getBalance());
            ps.setInt(3, profile.getWins());
            ps.setInt(4, profile.getLosses());
            ps.setInt(5, profile.getTies());
            ps.setInt(6, profile.getId());
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            throw new RuntimeException("Failed to update player", e);
        }
    }

    /**
     * Deletes a player profile by id.
     *
     * @param id player id to delete
     * @return {@code true} if the row was deleted, {@code false} if not found
     */
    public boolean delete(int id) {
        String sql = "DELETE FROM players WHERE id = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, id);
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            throw new RuntimeException("Failed to delete player", e);
        }
    }
}
